### ISSUE TITLE
Coinbase fails jest

### ISSUE THREAD

**Issue by tvb** [nicka/coinboss#14]
```
yarn jest
```
results in:
```
 FAIL  lib/coinbase.test.jsssed, 3 of 4 total
  ● Coinbase › buy or sell cryptocurrency › buy() › buys cryptocurrency

    Nock: No match for request {
      "method": "POST",
      "url": "https://api.coinbase.com/v2/accounts/4d264c58-6e3a-470a-93f9-5e1b6f3fafb0/buys",
      "headers": {
        "content-type": "application/json",
        "accept": "application/json",
        "user-agent": "coinbase/node/1.0.4",
        "cb-access-sign": "4e87966c5879d299db299e509d978cac8539e4b780195029492546cd75899356",
        "cb-access-timestamp": 1500877335,
        "cb-access-key": "lKAr9r62JWvTyjg4",
        "cb-version": "2016-02-18",
        "host": "api.coinbase.com",
        "content-length": 101
      },
      "body": "{\"total\":\"50\",\"currency\":\"EUR\",\"payment_method\":\"256a4697-62de-4f85-abee-256b67b621b8\",\"commit\":true}"
    }

      at end (node_modules/nock/lib/request_overrider.js:260:17)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.Object.<anonymous>.Request.end (node_modules/coinbase/node_modules/request/request.js:1397:14)
      at end (node_modules/coinbase/node_modules/request/request.js:554:16)
      at Immediate._onImmediate (node_modules/coinbase/node_modules/request/request.js:581:7)
      at runCallback (timers.js:800:20)
      at tryOnImmediate (timers.js:762:5)
      at processImmediate [as _immediateCallback] (timers.js:733:5)

  ● Coinbase › buy or sell cryptocurrency › sell() › sells cryptocurrency

    Nock: No match for request {
      "method": "POST",
      "url": "https://api.coinbase.com/v2/accounts/4d264c58-6e3a-470a-93f9-5e1b6f3fafb0/sells",
      "headers": {
        "content-type": "application/json",
        "accept": "application/json",
        "user-agent": "coinbase/node/1.0.4",
        "cb-access-sign": "39d61fad728bbe2a9fd377bf07bdce15cf27d4f006ac50644a55c24afe1f4d1e",
        "cb-access-timestamp": 1500877335,
        "cb-access-key": "lKAr9r62JWvTyjg4",
        "cb-version": "2016-02-18",
        "host": "api.coinbase.com",
        "content-length": 101
      },
      "body": "{\"total\":\"50\",\"currency\":\"EUR\",\"payment_method\":\"256a4697-62de-4f85-abee-256b67b621b8\",\"commit\":true}"
    }

      at end (node_modules/nock/lib/request_overrider.js:260:17)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:160:7)
      at Request.Object.<anonymous>.Request.end (node_modules/coinbase/node_modules/request/request.js:1397:14)
      at end (node_modules/coinbase/node_modules/request/request.js:554:16)
      at Immediate._onImmediate (node_modules/coinbase/node_modules/request/request.js:581:7)
      at runCallback (timers.js:800:20)
      at tryOnImmediate (timers.js:762:5)
      at processImmediate [as _immediateCallback] (timers.js:733:5)

  Coinbase
    getExchangeRates()
      ✓ stores exchange rates within CloudWatch (37ms)
    buy or sell cryptocurrency
      buy()
        ✕ buys cryptocurrency (8ms)
      sell()
        ✕ sells cryptocurrency (4ms)
```
Running against master branch

**Comment by nicka** [comment]
Is your local branch correctly synced with master? The latest master commit worked just fine https://travis-ci.org/nicka/coinboss/builds/254612255?utm_source=github_status&utm_medium=notification.
